baseURL = 'https://ai-assisted-software-development.com/'
languageCode = 'en-us'
title = 'AI-Assisted Software Development'
capitalizeListTitles = false
theme = 'PaperMod'
contentDir = 'site-content'
